### ISSUE TITLE
Path to Stage 4!

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-symbol-predicates#11]
## Stage 4
 - [ ] committee approval
 - [ ] two implementations
   - [ ] Firefox
   - [ ] Chrome
   - [ ] Safari
   - [ ] node
   - [ ] babel
   - [ ] TypeScript
   - [ ] polyfills
 - [ ] significant in-the-field experience
 - [ ] ecma262 PR approved
 - [ ] prepare ecma262 PR
 - [ ] merge test262 tests
 - [ ] write test262 tests

## Stage 3
 - [ ] Resolve open questions:
    - [ ] #9
 - [ ] committee approval
 - [ ] spec editor signoff
 - [ ] spec reviewer signoff
 - [ ] receive implementor feedback

## ~~[Stage 2](https://github.com/tc39/proposals/commit/a683a46ffad80a6f64bdffd98865e66be4e74062)
 - [x] committee approval
 - [ ] spec reviewers selected
 - [x] spec text written

## ~~[Stage 1](https://github.com/tc39/proposals/commit/d87fa721b09dde797b088ca58ac6806e6bc0df27)~~
 - [x] committee approval
